### ISSUE TITLE
Binary for ARM64 running Ubuntu 22.04 and ROS Humble

### ISSUE THREAD

**Issue by rshu-bd** [bdaiinstitute/bosdyn_msgs#3]
I've built a new binary (`ros-humble-bosdyn-msgs_0.0.0-0jammy_arm64.deb`) for use on an ARM64 running Ubuntu 22.04 and ROS Humble. I don't see an equivalent one in the Releases. We use this to run the Spot ROS package on a CORE I/O.

It would be great to add this to the Releases of this repo.  What would be the best way to do this?

**Comment by Jaynkd** [comment]
@rshu-bd do you have instructions to build bos_dyn-msgs-humble-arm64.deb for spot core IO?

**Comment by rshu-bd** [comment]
I followed the steps from the readme but inside a docker container targeted for ARM64, I can provide the docker image I used. I also included the [ros-humble-bosdyn-msgs_0.0.0-0jammy_arm64.deb](https://github.com/bdaiinstitute/spot_ros2/pull/90/files#diff-40463179ec8ce169566f04c0eabd1280dc987519e339e87d5003e7468e41fd1e) in the PR https://github.com/bdaiinstitute/spot_ros2/pull/90. 
It should not be there, it would be great to have it as a release in this repo.

**Comment by Jaynkd** [comment]
@rshu-bd it seems like the .deb file is for spot core v3.2.0 and I am trying to use it on v3.3.0

**Comment by rshu-bd** [comment]
That is correct I built the .deb for v3.2.0. 

I followed the steps under `Create debian structure` in the following readme https://github.com/bdaiinstitute/bosdyn_msgs/blob/56c4d5f94142542f961be9e682c51c535ebe8886/README.md 


Could you create a .deb for v3.3.0? If not, I can create a docker image to create it. However, it takes a while to build the .deb, in my case I had run it over night

**Comment by Jaynkd** [comment]
my current approach is to use arm64v8/ros:humble-perception-jammy docker image and mount it as a volume to create this deb bosdyn_msg package inside it and then move it to spot core IO for testing.

Btw, thanks for the heads up about time, I wonder why it takes this long to build just a msg package 4-6 hours are alot.

**Comment by Jaynkd** [comment]
Hi, I was successfully able to create deb for v3.2.0 but with spot v3.3.0 I got the following error:

dh_auto_configure: error: cd .obj-aarch64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/aarch64-linux-gnu -DCMAKE_INSTALL_PREFIX=/opt/ros/humble -DAMENT_PREFIX_PATH=/opt/ros/humble -DCMAKE_PREFIX_PATH=/opt/ros/humble .. returned exit code 1
make[1]: *** [debian/rules:33: override_dh_auto_configure] Error 2
make[1]: Leaving directory '/workspace/src/bosdyn_msgs'
make: *** [debian/rules:27: binary] Error 2

**Comment by amessing-bdai** [comment]
@rshu-bd Can you make a PR with the dockerfile that you used and any documentation needed to run it? When the PR gets merged I can create the release (and can just grab the deb you linked).

**Comment by amessing-bdai** [comment]
@Jaynkd The spot_v3-3 branch is out of date with respect to the script that generates the messages. Creating a 3.3 release is on our timeline for the near future

**Comment by rshu-bd** [comment]
> @rshu-bd Can you make a PR with the dockerfile that you used and any documentation needed to run it? When the PR gets merged I can create the release (and can just grab the deb you linked).

@amessing-bdai Sorry for the delay, I missed this message. PR https://github.com/bdaiinstitute/bosdyn_msgs/pull/6 adds the Dockerfile and instructions.
